urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.defaults import page_not_found
from rest_framework import routers
from . import views, schedule_views
from . import ical_feeds

app_name = "crm"

router = routers.DefaultRouter()
router.register(r"articles", views.ArticleViewSet, "article")
router.register(r"schedules", schedule_views.ScheduleViewSet, "schedule")

urlpatterns = [
    path("", views.index, name="index"),
    path("new/", views.new, name="new"),
    path("edit/<int:article_pk>/", views.edit, name="edit"),
    path("api/schedules/date/<int:year>/<int:month>/<int:day>/", schedule_views.DateView.as_view(), name="schedules_date"),
    path("api/schedules/date/", page_not_found, name="schedules_date_template"),
    path("api/", include(router.urls)),
    path('all_schedules/feed.ics', ical_feeds.AllSchedulesFeed()),
    path("schedules/", schedule_views.index, name="schedules"),
]

models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    json = models.JSONField()
    owner = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    related_articles = models.ManyToManyField("Article")

    def __str__(self):
        return '{} {}'.format(type(self.json), self.json)

views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.conf import settings
from django.db.models import Q
from django.contrib.sites.shortcuts import get_current_site
from django.urls import reverse

from rest_framework import viewsets
from rest_framework import status
from rest_framework import permissions
from rest_framework import authentication
from rest_framework.response import Response
from rest_framework import pagination
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import generics

import django_filters.rest_framework
import json

from . import models, serializers


class CustomPagination(pagination.PageNumberPagination):
    page_size = 100
    page_size_query_param = 'page_size'

class ArticleViewSet(viewsets.ModelViewSet):
    queryset = models.Article.objects.none()
    serializer_class = serializers.ArticleSerializer
    permission_classes = [permissions.IsAuthenticated]
    authentication_classes = [authentication.SessionAuthentication, authentication.BasicAuthentication]
    #filter_backends = [filters.CustomSearchFilter]
    #filter_backends = [django_filters.rest_framework.DjangoFilterBackend]
    #filter_fields = ('json',)
    pagination_class = CustomPagination

    def list(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.all().order_by("-updated_at")
        return super().list(request, *args, **kwargs)

    def create(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.filter(owner=request.user)
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(owner=request.user)  # self.perform_create
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def retrieve(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.filter(owner=request.user)
        return super().retrieve(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.filter(owner=request.user)
        return super().update(request, *args, **kwargs)

    def partial_update(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.filter(owner=request.user)
        return super().partial_update(request, *args, **kwargs)

    def destroy(self, request, *args, **kwargs):
        self.queryset = models.Article.objects.filter(owner=request.user)
        return super().destroy(self, request, *args, **kwargs)


# https://github.com/zoonaka/dx/blob/master/corporate_number/views.py
# APIView is useful when edit each model
# ListAPIView is suitable for read only view


def index(request):
    current_site = get_current_site(request)
    site_name = current_site.name
    context = {'is_debug': settings.DEBUG, "site_name": site_name}
    return render(request, 'crm/index.html', context)

def new(request):
    current_site = get_current_site(request)
    site_name = current_site.name
    context = {'is_debug': settings.DEBUG, "site_name": site_name}
    return render(request, 'crm/edit.html', context)

def edit(request, article_pk):
    current_site = get_current_site(request)
    site_name = current_site.name
    api_url = reverse("crm:article-detail", args=[article_pk])
    context = {'is_debug': settings.DEBUG, "site_name": site_name, "api_url": api_url}
    return render(request, 'crm/edit.html', context)

templates/crm/edit.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %}New Article | {{ site_name }}{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
{# header #}
{% include 'theme/header.html' %}

<div id="app"></div>

{# footer #}
{% include 'theme/footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/vue@3.2.22/dist/vue.global{% if not is_debug %}.prod{% endif %}.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.26.1/axios.min.js" integrity="sha512-bPh3uwgU5qEMipS/VOmRqynnMXGGSRv+72H/N260MQeXZIK4PG48401Bsby9Nq5P5fz7hy5UGNmC/W1Z51h2GQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.0.2/marked.min.js" integrity="sha512-hzyXu3u+VDu/7vpPjRKFp9w33Idx7pWWNazPm+aCMRu26yZXFCby1gn1JxevVv3LDwnSbyKrvLo3JNdi4Qx1ww==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.6/purify.min.js" integrity="sha512-DJjvM/U3zCRpzrYboJgg23iLHapWcS2rlo7Ni18Cdv+FMs6b3gUF7hQihztj4uVkHHfUwk7dha97jVzRqUJ7hg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>document.csrf_token = {value: "{{ csrf_token }}"}</script>
<script>axios.defaults.headers.common['X-CSRFToken'] = document.csrf_token.value</script>
<script src="{% static 'crm/js/vue/article_edit.js' %}"></script>
<script>
  const App = {
    data() {
      return {
      }
    },
    methods: {
      go_to_list() {
        window.location.href = "{% url 'crm:index' %}";
      },
    },
    template: `
      <div class="container">
        <article_edit
          prop_url="{% if api_url %}{{ api_url }}{% else %}{% url 'crm:article-list' %}{% endif %}"
          @submitted="go_to_list"/>
      </div>
    `
  };
</script>

<script>
  const app = Vue.createApp(App);
  app.component('article_edit',article_edit);
  app.mount('#app');
</script>
{% endblock %}

templates/crm/index.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %}{{ site_name }}{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
{# header #}
{% include 'theme/header.html' %}

<div id="app"></div>

{# footer #}
{% include 'theme/footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/vue@3.2.22/dist/vue.global{% if not is_debug %}.prod{% endif %}.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.26.1/axios.min.js" integrity="sha512-bPh3uwgU5qEMipS/VOmRqynnMXGGSRv+72H/N260MQeXZIK4PG48401Bsby9Nq5P5fz7hy5UGNmC/W1Z51h2GQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.0.2/marked.min.js" integrity="sha512-hzyXu3u+VDu/7vpPjRKFp9w33Idx7pWWNazPm+aCMRu26yZXFCby1gn1JxevVv3LDwnSbyKrvLo3JNdi4Qx1ww==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.6/purify.min.js" integrity="sha512-DJjvM/U3zCRpzrYboJgg23iLHapWcS2rlo7Ni18Cdv+FMs6b3gUF7hQihztj4uVkHHfUwk7dha97jVzRqUJ7hg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>document.csrf_token = {value: "{{ csrf_token }}"}</script>
<script>axios.defaults.headers.common['X-CSRFToken'] = document.csrf_token.value</script>
<script src="{% static 'crm/js/vue/article_elem.js' %}"></script>
<script>
  const App = {
    props:[],
    data() {
      return {
        data: [],
        loading: false,
      }
    },
    methods: {
      _get:async function(data) {
          await axios.get("{% url 'crm:article-list' %}")
          .then((response) => {
              this.data = response.data.results;
          })
          .catch((error) => {
              alert(error)
          });
      },

      reload() {
          this.loading = true;
          this._get().then(() => {
              this.loading = false;
              this.$emit('loaded');
          })
      },
      article_clicked(pk) {
        window.location.href = "{% url 'crm:index' %}edit/"+pk+"/";
      },
    },

    mounted() {
      this.reload();
    },

    template: `
      <div class="container">
        <article_elem
          v-for="elem in data"
          :key="elem.pk"
          :json="elem.json"
          :url="elem.url"
          @to_edit="(url)=>{$emit('to_edit',url)}"
          @click="article_clicked(elem.pk)"
        />
      </div>
    `
  };
</script>

<script>
  const app = Vue.createApp(App);
  app.component('article_elem',article_elem);
  app.mount('#app');
</script>
{% endblock %}

templates/crm/schedules.html
{% extends "theme/base.html" %}
{% load static %}

{% block title %}{{ site_name }}{% endblock %}

{% block extra_css %}
{% endblock %}

{% block content %}
{# header #}
{% include 'theme/header.html' %}

<div id="app"></div>

{# footer #}
{% include 'theme/footer.html' %}

{% endblock %}

{% block extra_js %}
<script src="https://unpkg.com/vue@3.2.22/dist/vue.global{% if not is_debug %}.prod{% endif %}.js"></script>
<script src="https://unpkg.com/vue-i18n@9/dist/vue-i18n.global{% if not is_debug %}.prod{% endif %}.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.26.1/axios.min.js"
  integrity="sha512-bPh3uwgU5qEMipS/VOmRqynnMXGGSRv+72H/N260MQeXZIK4PG48401Bsby9Nq5P5fz7hy5UGNmC/W1Z51h2GQ=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/4.0.2/marked.min.js"
  integrity="sha512-hzyXu3u+VDu/7vpPjRKFp9w33Idx7pWWNazPm+aCMRu26yZXFCby1gn1JxevVv3LDwnSbyKrvLo3JNdi4Qx1ww=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.3.6/purify.min.js"
  integrity="sha512-DJjvM/U3zCRpzrYboJgg23iLHapWcS2rlo7Ni18Cdv+FMs6b3gUF7hQihztj4uVkHHfUwk7dha97jVzRqUJ7hg=="
  crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>document.csrf_token = { value: "{{ csrf_token }}" }</script>
<script>document.schedule_list_url = "{% url 'crm:schedule-list' %}"</script>
<script>document.schedules_date_url = "{% url 'crm:schedules_date_template'%}"</script>

<script>axios.defaults.headers.common['X-CSRFToken'] = document.csrf_token.value</script>

<script src="{% static 'crm/js/utils.js' %}"></script>
<script src="{% static 'crm/js/vue/app.js' %}"></script>
<script src="{% static 'crm/js/vue/schedule_elem.js' %}"></script>
<script src="{% static 'crm/js/vue/schedule_edit_modal.js' %}"></script>
<script src="{% static 'crm/js/vue/schedule_date.js' %}"></script>

<script>
  const messages = {
    en: {
      labels: {
        title: 'Title',
        all_day: 'All Day',
        start_datetime: "Start Datetime",
        end_datetime: "End Datetime",
        note: "Note",
        submit: "Submit",
        delete: "Delete",
        edit: "Edit",
      }
    },
    ja: {
      labels: {
        title: 'タイトル',
        all_day: "終日",
        start_datetime: "開始日時",
        end_datetime: "終了日時",
        note: "メモ",
        submit: "登録",
        delete: "削除",
        edit: "編集",
      }
    }
  }

  const i18n = VueI18n.createI18n({
    locale: 'ja', // set locale
    messages, // set locale messages
  })
</script>

<script>
  const app = Vue.createApp(App);
  app.use(i18n);
  app.component('schedule_elem', schedule_elem);
  app.component('schedule_edit_modal', schedule_edit_modal);
  app.component('schedule_date', schedule_date);
  app.mount('#app');
</script>
{% endblock %}